import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { getInstallStatePath, getLawalletStateDir, getWebDir } from './paths.js'
import { buildAppHealthUrl, buildAppUrl, buildDatabaseUrl } from './shared.js'

export function buildInstallState({
  repoRoot,
  mode,
  appPort,
  postgresPort,
  postgresUser,
  postgresPassword,
  postgresDatabase,
  jwtSecret,
  composeProjectName
}) {
  return {
    version: 1,
    installedAt: new Date().toISOString(),
    repoRoot,
    mode,
    composeProjectName,
    app: {
      port: appPort,
      url: buildAppUrl(appPort),
      healthUrl: buildAppHealthUrl(appPort)
    },
    postgres: {
      host: '127.0.0.1',
      port: postgresPort,
      user: postgresUser,
      password: postgresPassword,
      database: postgresDatabase,
      adminDatabase: 'postgres'
    },
    jwtSecret,
    paths: {
      webDir: getWebDir(repoRoot)
    }
  }
}

export async function readInstallState(repoRoot) {
  try {
    const file = await readFile(getInstallStatePath(repoRoot), 'utf8')
    return JSON.parse(file)
  } catch {
    return null
  }
}

export async function writeInstallState(repoRoot, state) {
  await mkdir(getLawalletStateDir(repoRoot), { recursive: true })
  await writeFile(
    getInstallStatePath(repoRoot),
    `${JSON.stringify(state, null, 2)}\n`,
    'utf8'
  )
}

export async function writeRootEnvFile(repoRoot, state) {
  const contents = [
    `COMPOSE_PROJECT_NAME=${state.composeProjectName}`,
    `POSTGRES_DB=${state.postgres.database}`,
    `POSTGRES_USER=${state.postgres.user}`,
    `POSTGRES_PASSWORD=${state.postgres.password}`,
    `POSTGRES_PORT=${state.postgres.port}`,
    `PORT=${state.app.port}`,
    `NODE_ENV=production`,
    `JWT_SECRET=${state.jwtSecret}`
  ].join('\n')

  await writeFile(path.join(repoRoot, '.env'), `${contents}\n`, 'utf8')
}

export async function writeNativeEnvFile(repoRoot, state) {
  const contents = [
    '# Generated by the LaWallet CLI',
    `DATABASE_URL="${buildDatabaseUrl(state)}"`,
    `JWT_SECRET="${state.jwtSecret}"`,
    'NODE_ENV="production"',
    `PORT="${state.app.port}"`
  ].join('\n')

  await writeFile(path.join(getWebDir(repoRoot), '.env'), `${contents}\n`, 'utf8')
}
