import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import {
  getDocsDir,
  getInstallStatePath,
  getLawalletStateDir,
  getOpenapiDir,
  getWebDir
} from './paths.js'
import {
  DEFAULT_DOCS_PORT,
  DEFAULT_OPENAPI_PORT,
  DEFAULT_WEB_PORT,
  buildAppHealthUrl,
  buildAppUrl,
  buildDatabaseUrl,
  buildDocsHealthUrl,
  buildOpenApiHealthUrl
} from './shared.js'

function buildServiceRecord(port, buildHealthUrl) {
  return {
    port,
    url: buildAppUrl(port),
    healthUrl: buildHealthUrl(port)
  }
}

function buildServiceMap({
  webPort,
  docsPort,
  openapiPort
}) {
  return {
    web: buildServiceRecord(webPort, buildAppHealthUrl),
    docs: buildServiceRecord(docsPort, buildDocsHealthUrl),
    openapi: buildServiceRecord(openapiPort, buildOpenApiHealthUrl)
  }
}

function normalizeInstallState(repoRoot, rawState) {
  const webPort = rawState?.services?.web?.port ?? rawState?.app?.port ?? DEFAULT_WEB_PORT
  const docsPort = rawState?.services?.docs?.port ?? DEFAULT_DOCS_PORT
  const openapiPort = rawState?.services?.openapi?.port ?? DEFAULT_OPENAPI_PORT
  const services = buildServiceMap({
    webPort,
    docsPort,
    openapiPort
  })

  return {
    ...rawState,
    app: services.web,
    services,
    paths: {
      ...rawState?.paths,
      webDir: getWebDir(repoRoot),
      docsDir: getDocsDir(repoRoot),
      openapiDir: getOpenapiDir(repoRoot)
    }
  }
}

export function buildInstallState({
  repoRoot,
  mode,
  appPort,
  docsPort,
  openapiPort,
  postgresPort,
  postgresUser,
  postgresPassword,
  postgresDatabase,
  jwtSecret,
  keyVaultSecret,
  composeProjectName
}) {
  const services = buildServiceMap({
    webPort: appPort,
    docsPort,
    openapiPort
  })

  return {
    version: 2,
    installedAt: new Date().toISOString(),
    repoRoot,
    mode,
    composeProjectName,
    app: services.web,
    services,
    postgres: {
      host: '127.0.0.1',
      port: postgresPort,
      user: postgresUser,
      password: postgresPassword,
      database: postgresDatabase,
      adminDatabase: 'postgres'
    },
    jwtSecret,
    keyVaultSecret,
    paths: {
      webDir: getWebDir(repoRoot),
      docsDir: getDocsDir(repoRoot),
      openapiDir: getOpenapiDir(repoRoot)
    }
  }
}

export async function readInstallState(repoRoot) {
  try {
    const file = await readFile(getInstallStatePath(repoRoot), 'utf8')
    return normalizeInstallState(repoRoot, JSON.parse(file))
  } catch {
    return null
  }
}

export async function writeInstallState(repoRoot, state) {
  await mkdir(getLawalletStateDir(repoRoot), { recursive: true })
  await writeFile(
    getInstallStatePath(repoRoot),
    `${JSON.stringify(state, null, 2)}\n`,
    'utf8'
  )
}

export async function writeRootEnvFile(repoRoot, state) {
  const contents = [
    `COMPOSE_PROJECT_NAME=${state.composeProjectName}`,
    `POSTGRES_DB=${state.postgres.database}`,
    `POSTGRES_USER=${state.postgres.user}`,
    `POSTGRES_PASSWORD=${state.postgres.password}`,
    `POSTGRES_PORT=${state.postgres.port}`,
    `PORT=${state.app.port}`,
    `DOCS_PORT=${state.services.docs.port}`,
    `OPENAPI_PORT=${state.services.openapi.port}`,
    `OPENAPI_SERVER_URL=${state.app.url}`,
    `NODE_ENV=production`,
    `JWT_SECRET=${state.jwtSecret}`,
    // Older install states predate the key vault; omit rather than write an
    // empty value so passkey signup reports "not configured" cleanly.
    ...(state.keyVaultSecret ? [`KEY_VAULT_SECRET=${state.keyVaultSecret}`] : [])
  ].join('\n')

  await writeFile(path.join(repoRoot, '.env'), `${contents}\n`, 'utf8')
}

export async function writeNativeEnvFile(repoRoot, state) {
  const contents = [
    '# Generated by the LaWallet CLI',
    `DATABASE_URL="${buildDatabaseUrl(state)}"`,
    `JWT_SECRET="${state.jwtSecret}"`,
    ...(state.keyVaultSecret
      ? [`KEY_VAULT_SECRET="${state.keyVaultSecret}"`]
      : []),
    'NODE_ENV="production"',
    `PORT="${state.app.port}"`
  ].join('\n')

  await writeFile(path.join(getWebDir(repoRoot), '.env'), `${contents}\n`, 'utf8')
}
