// Side-effect imports: each module calls `registry.registerPath()` for its
// resource group. Keep this file a flat list; ordering doesn't matter because
// path registration is independent across files.
import './auth'
import './cards'
import './card-activation'
import './card-designs'
import './lightning-addresses'
import './lud16'
import './wallet'
import './users'
import './invoices'
import './settings'
import './admin'
import './setup'
import './version'
import './remote-connections'
import './remote-wallets'
import './activity'
import './events'
