#!/usr/bin/env bash
set -euo pipefail

umask 077

usage() {
  cat <<'USAGE'
Generate production-ready LaWallet deployment environment files.

Usage:
  ./scripts/generate-deployment-env.sh [options]

Options:
  --mode compose|cloud  compose writes one Docker/Coolify .env file.
                        cloud writes separate web.env and listener.env files.
                        Default: compose
  --output PATH         Output file for compose mode or directory for cloud.
                        Defaults: .env or lawallet-cloud-env
  --help                Show this help.

The script never overwrites an existing file or directory.
USAGE
}

mode="compose"
output=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      [[ $# -ge 2 ]] || {
        echo "Missing value for --mode." >&2
        exit 2
      }
      mode="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || {
        echo "Missing value for --output." >&2
        exit 2
      }
      output="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$mode" != "compose" && "$mode" != "cloud" ]]; then
  echo "--mode must be compose or cloud." >&2
  exit 2
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate deployment secrets." >&2
  exit 1
fi

random_secret() {
  openssl rand -hex 32
}

# Generate every secret independently. Values shared between web and listener
# are generated once here and written unchanged into both cloud files.
postgres_password="$(random_secret)"
jwt_secret="$(random_secret)"
key_vault_secret="$(random_secret)"
nwc_vault_secret="$(random_secret)"
listener_auth_secret="$(random_secret)"
listener_request_auth_secret="$(random_secret)"

if [[ "$mode" == "compose" ]]; then
  output="${output:-.env}"

  if [[ -e "$output" ]]; then
    echo "Refusing to overwrite existing path: $output" >&2
    exit 1
  fi

  output_parent="$(dirname "$output")"
  mkdir -p "$output_parent"
  temp_file="$(mktemp "${output}.tmp.XXXXXX")"
  trap 'rm -f "$temp_file"' EXIT

  cat >"$temp_file" <<EOF
# Generated by scripts/generate-deployment-env.sh
# Keep this file private, back it up, and never commit it.

# Published image and ports
LAWALLET_TAG=latest
NODE_ENV=production
PORT=2288
LISTENER_PORT=4100

# Start the bundled listener profile.
COMPOSE_PROFILES=listener
LISTENER_URL=http://listener:4100

# Bundled PostgreSQL
POSTGRES_DB=lawallet
POSTGRES_USER=lawallet
POSTGRES_PASSWORD=$postgres_password

# Web authentication
JWT_SECRET=$jwt_secret

# Optional user-key vault. Independent from the NWC vault.
KEY_VAULT_SECRET=$key_vault_secret
KEY_VAULT_SECRET_PREVIOUS=

# RemoteWallet + deferred proxy NWC vault. Web and listener must match.
NWC_VAULT_SECRET=$nwc_vault_secret
NWC_VAULT_SECRET_PREVIOUS=

# Listener HMAC and request authentication. Web and listener must match.
LISTENER_AUTH_SECRET=$listener_auth_secret
LISTENER_REQUEST_AUTH_SECRET=$listener_request_auth_secret

# The NIP-57 receipt signer nsec is intentionally absent.
# Configure it as a write-only value in Admin -> Settings -> NWC Services.
EOF

  mv "$temp_file" "$output"
  trap - EXIT
  chmod 600 "$output"

  echo "Created $output (mode 600)."
  echo "Start the full stack with:"
  echo "  docker compose -f docker-compose.hub.yml up -d"
  exit 0
fi

output="${output:-lawallet-cloud-env}"
if [[ -e "$output" ]]; then
  echo "Refusing to overwrite existing path: $output" >&2
  exit 1
fi

output_parent="$(dirname "$output")"
mkdir -p "$output_parent"
temp_directory="$(mktemp -d "${output}.tmp.XXXXXX")"
trap 'rm -rf "$temp_directory"' EXIT
web_file="$temp_directory/web.env"
listener_file="$temp_directory/listener.env"

cat >"$web_file" <<EOF
# Web environment for Vercel, Netlify, or another web host.
# Replace URL placeholders before deploying.
DATABASE_URL=REPLACE_WITH_POSTGRES_CONNECTION_STRING
NODE_ENV=production
JWT_SECRET=$jwt_secret
KEY_VAULT_SECRET=$key_vault_secret
KEY_VAULT_SECRET_PREVIOUS=
NWC_VAULT_SECRET=$nwc_vault_secret
NWC_VAULT_SECRET_PREVIOUS=
LISTENER_URL=REPLACE_WITH_HTTPS_LISTENER_URL
LISTENER_AUTH_SECRET=$listener_auth_secret
LISTENER_REQUEST_AUTH_SECRET=$listener_request_auth_secret

# Configure the NIP-57 receipt signer nsec in Admin Settings, not here.
EOF

cat >"$listener_file" <<EOF
# Listener environment for an always-on container host.
# Replace URL placeholders before deploying.
DATABASE_URL=REPLACE_WITH_THE_SAME_POSTGRES_CONNECTION_STRING
WEB_ORIGIN=REPLACE_WITH_HTTPS_WEB_ORIGIN
NODE_ENV=production
LISTENER_PORT=4100
LISTENER_AUTH_SECRET=$listener_auth_secret
LISTENER_REQUEST_AUTH_SECRET=$listener_request_auth_secret
NWC_VAULT_SECRET=$nwc_vault_secret
NWC_VAULT_SECRET_PREVIOUS=
PROXY_RECONCILE_INTERVAL_MS=600000

# The listener never receives the NIP-57 receipt signer nsec.
EOF

chmod 600 "$web_file" "$listener_file"
mv "$temp_directory" "$output"
trap - EXIT

echo "Created cloud environment bundle in $output/:"
echo "  $output/web.env"
echo "  $output/listener.env"
echo "Replace the URL/database placeholders, then copy each file to its host."
