// Generated by scripts/docs-sync.mjs — do not edit.
// Regenerate with `node scripts/docs-sync.mjs --write --manifest-only`.
//
// OpenAPI path template → lazy import of its route module, so MCP tool
// calls can run the real REST handler in-process.

type RouteModule = Record<string, unknown>

/* v8 ignore start -- generated loaders, exercised through dispatch */
export const routeManifest: Record<string, () => Promise<RouteModule>> = {
  '/api/account': () => import('@/app/api/account/route'),
  '/api/account/identities/link/begin': () =>
    import('@/app/api/account/identities/link/begin/route'),
  '/api/account/identities/link/verify': () =>
    import('@/app/api/account/identities/link/verify/route'),
  '/api/account/identities/{pubkey}': () =>
    import('@/app/api/account/identities/[pubkey]/route'),
  '/api/account/merge': () => import('@/app/api/account/merge/route'),
  '/api/account/merge/preview': () =>
    import('@/app/api/account/merge/preview/route'),
  '/api/activation-tokens/{id}': () =>
    import('@/app/api/activation-tokens/[id]/route'),
  '/api/activation-tokens/{id}/claim': () =>
    import('@/app/api/activation-tokens/[id]/claim/route'),
  '/api/activity': () => import('@/app/api/activity/route'),
  '/api/admin/assign': () => import('@/app/api/admin/assign/route'),
  '/api/admin/backup/analyze': () =>
    import('@/app/api/admin/backup/analyze/route'),
  '/api/admin/backup/export': () =>
    import('@/app/api/admin/backup/export/route'),
  '/api/admin/backup/import': () =>
    import('@/app/api/admin/backup/import/route'),
  '/api/admin/listener/status': () =>
    import('@/app/api/admin/listener/status/route'),
  '/api/auth/passkey/credentials': () =>
    import('@/app/api/auth/passkey/credentials/route'),
  '/api/auth/passkey/credentials/{id}': () =>
    import('@/app/api/auth/passkey/credentials/[id]/route'),
  '/api/auth/passkey/registration/options': () =>
    import('@/app/api/auth/passkey/registration/options/route'),
  '/api/auth/passkey/registration/verify': () =>
    import('@/app/api/auth/passkey/registration/verify/route'),
  '/api/auth/qr-jwt/generate': () =>
    import('@/app/api/auth/qr-jwt/generate/route'),
  '/api/card-designs': () => import('@/app/api/card-designs/route'),
  '/api/card-designs/count': () => import('@/app/api/card-designs/count/route'),
  '/api/card-designs/get/{id}': () =>
    import('@/app/api/card-designs/get/[id]/route'),
  '/api/card-designs/import': () =>
    import('@/app/api/card-designs/import/route'),
  '/api/card-designs/import-veintiuno': () =>
    import('@/app/api/card-designs/import-veintiuno/route'),
  '/api/card-designs/list': () => import('@/app/api/card-designs/list/route'),
  '/api/card-designs/{id}': () => import('@/app/api/card-designs/[id]/route'),
  '/api/cards': () => import('@/app/api/cards/route'),
  '/api/cards/counts': () => import('@/app/api/cards/counts/route'),
  '/api/cards/otc/{otc}': () => import('@/app/api/cards/otc/[otc]/route'),
  '/api/cards/otc/{otc}/activate': () =>
    import('@/app/api/cards/otc/[otc]/activate/route'),
  '/api/cards/{id}': () => import('@/app/api/cards/[id]/route'),
  '/api/cards/{id}/activation-tokens': () =>
    import('@/app/api/cards/[id]/activation-tokens/route'),
  '/api/cards/{id}/emulate-tap': () =>
    import('@/app/api/cards/[id]/emulate-tap/route'),
  '/api/cards/{id}/lnurlp': () => import('@/app/api/cards/[id]/lnurlp/route'),
  '/api/cards/{id}/lnurlp/cb': () =>
    import('@/app/api/cards/[id]/lnurlp/cb/route'),
  '/api/cards/{id}/rescue': () => import('@/app/api/cards/[id]/rescue/route'),
  '/api/cards/{id}/scan': () => import('@/app/api/cards/[id]/scan/route'),
  '/api/cards/{id}/scan/cb': () => import('@/app/api/cards/[id]/scan/cb/route'),
  '/api/cards/{id}/transactions': () =>
    import('@/app/api/cards/[id]/transactions/route'),
  '/api/cards/{id}/wipe': () => import('@/app/api/cards/[id]/wipe/route'),
  '/api/cards/{id}/write': () => import('@/app/api/cards/[id]/write/route'),
  '/api/cards/{id}/write-token': () =>
    import('@/app/api/cards/[id]/write-token/route'),
  '/api/health': () => import('@/app/api/health/route'),
  '/api/invoices': () => import('@/app/api/invoices/route'),
  '/api/invoices/{id}/claim': () =>
    import('@/app/api/invoices/[id]/claim/route'),
  '/api/jwt': () => import('@/app/api/jwt/route'),
  '/api/jwt/protected': () => import('@/app/api/jwt/protected/route'),
  '/api/lightning-addresses': () =>
    import('@/app/api/lightning-addresses/route'),
  '/api/lightning-addresses/check': () =>
    import('@/app/api/lightning-addresses/check/route'),
  '/api/lightning-addresses/counts': () =>
    import('@/app/api/lightning-addresses/counts/route'),
  '/api/lightning-addresses/relays': () =>
    import('@/app/api/lightning-addresses/relays/route'),
  '/api/lightning-addresses/verify-protocols': () =>
    import('@/app/api/lightning-addresses/verify-protocols/route'),
  '/api/lud16/{username}': () => import('@/app/api/lud16/[username]/route'),
  '/api/lud16/{username}/cb': () =>
    import('@/app/api/lud16/[username]/cb/route'),
  '/api/lud16/{username}/verify/{paymentHash}': () =>
    import('@/app/api/lud16/[username]/verify/[paymentHash]/route'),
  '/api/nostr/profiles': () => import('@/app/api/nostr/profiles/route'),
  '/api/openapi.json': () => import('@/app/api/openapi.json/route'),
  '/api/plugins': () => import('@/app/api/plugins/route'),
  '/api/plugins/{plugin}': () => import('@/app/api/plugins/[plugin]/route'),
  '/api/remote-connections/{externalDeviceKey}': () =>
    import('@/app/api/remote-connections/[externalDeviceKey]/route'),
  '/api/remote-connections/{externalDeviceKey}/cards': () =>
    import('@/app/api/remote-connections/[externalDeviceKey]/cards/route'),
  '/api/remote-wallets': () => import('@/app/api/remote-wallets/route'),
  '/api/remote-wallets/forwarding-map': () =>
    import('@/app/api/remote-wallets/forwarding-map/route'),
  '/api/remote-wallets/lncurl': () =>
    import('@/app/api/remote-wallets/lncurl/route'),
  '/api/remote-wallets/{id}': () =>
    import('@/app/api/remote-wallets/[id]/route'),
  '/api/remote-wallets/{id}/balance': () =>
    import('@/app/api/remote-wallets/[id]/balance/route'),
  '/api/remote-wallets/{id}/connection-string': () =>
    import('@/app/api/remote-wallets/[id]/connection-string/route'),
  '/api/remote-wallets/{id}/forwarding-activity': () =>
    import('@/app/api/remote-wallets/[id]/forwarding-activity/route'),
  '/api/remote-wallets/{id}/forwarding-receipts': () =>
    import('@/app/api/remote-wallets/[id]/forwarding-receipts/route'),
  '/api/remote-wallets/{id}/forwarding-receipts/{receiptId}': () =>
    import('@/app/api/remote-wallets/[id]/forwarding-receipts/[receiptId]/route'),
  '/api/remote-wallets/{id}/forwarding-receipts/{receiptId}/retry': () =>
    import('@/app/api/remote-wallets/[id]/forwarding-receipts/[receiptId]/retry/route'),
  '/api/remote-wallets/{id}/notification-deliveries': () =>
    import('@/app/api/remote-wallets/[id]/notification-deliveries/route'),
  '/api/remote-wallets/{id}/notification-deliveries/{deliveryId}/retry': () =>
    import('@/app/api/remote-wallets/[id]/notification-deliveries/[deliveryId]/retry/route'),
  '/api/remote-wallets/{id}/notifications': () =>
    import('@/app/api/remote-wallets/[id]/notifications/route'),
  '/api/remote-wallets/{id}/notifications/{notificationId}': () =>
    import('@/app/api/remote-wallets/[id]/notifications/[notificationId]/route'),
  '/api/remote-wallets/{id}/payments/{paymentHash}': () =>
    import('@/app/api/remote-wallets/[id]/payments/[paymentHash]/route'),
  '/api/remote-wallets/{id}/receive-action': () =>
    import('@/app/api/remote-wallets/[id]/receive-action/route'),
  '/api/remote-wallets/{id}/receive-action/force': () =>
    import('@/app/api/remote-wallets/[id]/receive-action/force/route'),
  '/api/settings': () => import('@/app/api/settings/route'),
  '/api/settings/domain-probe': () =>
    import('@/app/api/settings/domain-probe/route'),
  '/api/settings/listener-probe': () =>
    import('@/app/api/settings/listener-probe/route'),
  '/api/settings/lud16-proxy': () =>
    import('@/app/api/settings/lud16-proxy/route'),
  '/api/settings/lud16-proxy/payments': () =>
    import('@/app/api/settings/lud16-proxy/payments/route'),
  '/api/settings/lud16-proxy/payments/{id}/retry': () =>
    import('@/app/api/settings/lud16-proxy/payments/[id]/retry/route'),
  '/api/settings/lud16-proxy/test': () =>
    import('@/app/api/settings/lud16-proxy/test/route'),
  '/api/setup/status': () => import('@/app/api/setup/status/route'),
  '/api/users': () => import('@/app/api/users/route'),
  '/api/users/me': () => import('@/app/api/users/me/route'),
  '/api/users/me/currency-prefs': () =>
    import('@/app/api/users/me/currency-prefs/route'),
  '/api/users/{userId}': () => import('@/app/api/users/[userId]/route'),
  '/api/users/{userId}/cards': () =>
    import('@/app/api/users/[userId]/cards/route'),
  '/api/users/{userId}/lightning-address': () =>
    import('@/app/api/users/[userId]/lightning-address/route'),
  '/api/users/{userId}/relays': () =>
    import('@/app/api/users/[userId]/relays/route'),
  '/api/users/{userId}/role': () =>
    import('@/app/api/users/[userId]/role/route'),
  '/api/version': () => import('@/app/api/version/route'),
  '/api/vouchers': () => import('@/app/api/vouchers/route'),
  '/api/wallet/addresses': () => import('@/app/api/wallet/addresses/route'),
  '/api/wallet/addresses/alias-probe': () =>
    import('@/app/api/wallet/addresses/alias-probe/route'),
  '/api/wallet/addresses/{username}': () =>
    import('@/app/api/wallet/addresses/[username]/route'),
  '/api/wallet/addresses/{username}/invoices': () =>
    import('@/app/api/wallet/addresses/[username]/invoices/route'),
  '/api/wallet/addresses/{username}/invoices/{invoiceId}/forwarding': () =>
    import('@/app/api/wallet/addresses/[username]/invoices/[invoiceId]/forwarding/route'),
  '/api/wallet/addresses/{username}/primary': () =>
    import('@/app/api/wallet/addresses/[username]/primary/route'),
  '/api/wallet/addresses/{username}/proxy-balance': () =>
    import('@/app/api/wallet/addresses/[username]/proxy-balance/route'),
  '/api/wallet/cards': () => import('@/app/api/wallet/cards/route'),
  '/api/wallet/cards/{id}': () => import('@/app/api/wallet/cards/[id]/route'),
  '/api/wallet/vouchers': () => import('@/app/api/wallet/vouchers/route'),
  '/api/wallet/vouchers/settings': () =>
    import('@/app/api/wallet/vouchers/settings/route'),
  '/api/wallet/vouchers/{id}': () =>
    import('@/app/api/wallet/vouchers/[id]/route'),
  '/api/wallet/vouchers/{id}/refresh': () =>
    import('@/app/api/wallet/vouchers/[id]/refresh/route'),
  '/api/wallet/vouchers/{id}/send': () =>
    import('@/app/api/wallet/vouchers/[id]/send/route')
}
/* v8 ignore stop */
